[package]
name = "monarch-butterfly"
version = "0.2.0"
edition = "2021"
description = "Proc-Macro unrolled FFTs"
license = "MIT"
documentation = "https://docs.rs/monarch-butterfly"
homepage = "https://github.com/michaelciraci/Monarch-Butterfly"
repository = "https://github.com/michaelciraci/Monarch-Butterfly"
rust-version = "1.63"

[dependencies]
monarch-derive = { path = "crates/monarch-derive" }
num-complex = "0.4"
num-traits = "0.2"

[dev-dependencies]
rustfft = "6.2.0"
