[package]
name = "butterfly"
version = "0.1.0"
edition = "2024"

[dependencies]
num-complex = "0.4.6"

[dev-dependencies]
criterion = "0.5.1"
rustfft = "6.2.0"

[[bench]]
name = "comparison"
harness = false
