[package]
name = "monarch-butterfly"
version = "0.1.0"
edition = "2021"
description = "FFTs for powers of 2"
license = "MIT"

[dependencies]
num-complex = "0.4"

[dev-dependencies]
criterion = "0.5"
rustfft = { version = "6.2.0", default-features = false }

[[bench]]
name = "comparison"
harness = false
