[package]
name = "monarch-butterfly"
version = "0.1.0"
edition = "2018"

[dependencies]
num-complex = "0.4"

[dev-dependencies]
criterion = "0.5"
rustfft = "6.2.0"

[[bench]]
name = "comparison"
harness = false
