[package]
name = "benches"
version = "0.1.0"
edition = "2024"

[dependencies]
monarch-butterfly = { path = "../../" }
num-complex = "0.4.6"

[dev-dependencies]
criterion = "0.5"
fftw = "0.8.0"
rustfft = "6.2.0"

[[bench]]
name = "comparison"
harness = false
